data:extend({
    {
        type = "item",
        name = "Paper",
        icon = "__PokemonTCGFactory__/graphics/icons/paper.png",
        icon_size = 64,
        subgroup = "cards",
        flags = {"goes-to-quickbar"},
        stack_size = 999,
    },
    {
        type = "item",
        name = "Ink",
        icon = "__PokemonTCGFactory__/graphics/icons/Ink.png",
        icon_size = 64,
        subgroup = "cards",
        flags = {"goes-to-quickbar"},
        stack_size = 999,
    },
    {
        type = "item",
        name = "Pokemon-Card",
        icon = "__PokemonTCGFactory__/graphics/icons/PokemonCard.png",
        icon_size = 64,
        subgroup = "cards",
        flags = {"goes-to-quickbar"},
        stack_size = 999,
    },
    {
        type = "item",
        name = "Pokemon-Booster-Pack",
        icon = "__PokemonTCGFactory__/graphics/icons/BoosterPack.png",
        icon_size = 64,
        subgroup = "cards",
        flags = {"goes-to-quickbar"},
        stack_size = 999,
    },
    {
        type = "item",
        name = "Pokemon-Booster-Box",
        icon = "__PokemonTCGFactory__/graphics/icons/BoosterBox.png",
        icon_size = 64,
        subgroup = "cards",
        flags = {"goes-to-quickbar"},
        stack_size = 999,
    }
})